### ISSUE TITLE
AttributeError: 'AskFileResponse' object has no attribute 'content'

### ISSUE THREAD

**Issue by liu-xiao-guo** [sudarshan-koirala/langchain-openai-chainlit#4]
I tried to run the code. However, I get the error like:

`AttributeError: 'AskFileResponse' object has no attribute 'content'`    

in the code 

`pdf_stream = BytesIO(file.content)`

According to the source code at https://github.com/Chainlit/chainlit/blob/4c08c24c807ac5e075646845827c9826bbed888a/backend/chainlit/types.py#L88, AskFileResponse does not have the attribute of "content"

```
class AskFileResponse:
    id: str
    name: str
    path: str
    size: int
    type: str
```

<img width="1150" alt="image" src="https://github.com/sudarshan-koirala/langchain-openai-chainlit/assets/8455957/b3e8758c-372a-4cf9-8c99-b6359244cadf">

How to resolve this issue?

Thanks

**Comment by ahmed-danjuma-ibn-harun** [comment]
The updated version of chainlit "AskFileResponse" doesn't comes with a "content" attribute anymore, rather you can open "file.path" using this format:

for text and pdf files, you can use:

with open(text_file.path, "r", encoding="utf-8") as f:
        content= f.read()

and for csv files:
import pandas as pd
content = pd.read_csv(file.path)

**Comment by sudarshan-koirala** [comment]
@liu-xiao-guo , the packages used will be constantly updating, but can you try this, it should work. 

![image](https://github.com/sudarshan-koirala/langchain-openai-chainlit/assets/14214659/36c9d3e6-c617-49e0-8fd3-7bd20f2a7199)

**Comment by liu-xiao-guo** [comment]
Thanks. I have actually changed the code as follows:

```
   with open(file.path, 'rb') as f:
        pdf_content = f.read()
    pdf_stream = BytesIO(pdf_content)
    pdf = PyPDF2.PdfReader(pdf_stream)
    pdf_text = ""
    for page in pdf.pages:
        pdf_text += page.extract_text()
```

Now, I can see the embeddings. However, I have another issue when running the app. My forked code is at https://github.com/liu-xiao-guo/langchain-openai-chainlit. I am using Elasticsearch for the testing.

**Comment by liu-xiao-guo** [comment]
I use pdf_qa.py as an example. I got an error like:
<img width="1421" alt="image" src="https://github.com/sudarshan-koirala/langchain-openai-chainlit/assets/8455957/b3feaa8f-e909-4b7a-93fe-be8d06800e54">

I do not know what is the root cause of the problem.

**Comment by liu-xiao-guo** [comment]
I finally made the code working for the Elasticsearch. I need to change one line of code in the pdf_qa.py:

<img width="749" alt="image" src="https://github.com/sudarshan-koirala/langchain-openai-chainlit/assets/8455957/3c4b9b1b-1544-4245-b339-3bc2c33bcfea">


```
    print("message: ", message)
    pprint(vars(message))
    print(message.content)
    res = await chain.acall(message.content, callbacks=[cb])
```

**Comment by sudarshan-koirala** [comment]
@liu-xiao-guo Glad that you fixed it.
